const HAS_SESSION = 'HAS_SESSION';
const LOGGEDIN_USER_DATA = 'LOGGEDIN_USER_DATA';
const LOGGEDIN_NUMBER = 'LOGGEDIN_NUMBER';
const LOGOUT = 'LOGOUT';
const COUNTRIES_DATA = 'COUNTRIES_DATA';
const ID_DOCUMENT_FILE = 'ID_DOCUMENT_FILE'
const EDU_DOCUMENT_FILE = 'EDU_DOCUMENT_FILE'
const REV_DOCUMENT_FILE = 'REV_DOCUMENT_FILE'

export {
  //
  HAS_SESSION,
  LOGOUT,
  LOGGEDIN_USER_DATA,
  COUNTRIES_DATA,
  LOGGEDIN_NUMBER,
  ID_DOCUMENT_FILE,
  EDU_DOCUMENT_FILE,
  REV_DOCUMENT_FILE
  //

};
